# syntax=docker/dockerfile:1.7

FROM node:22-bookworm-slim AS base
WORKDIR /usr/src/app

ENV NODE_ENV=test

COPY package.json ./
RUN npm install

COPY nest-cli.json tsconfig*.json ./
COPY src ./src
COPY test ./test

CMD ["sh", "-c", "npm run test && npm run test:e2e"]
