services:
  mongodb:
    volumes: []

  tests:
    build:
      context: ..
      dockerfile: docker/images/api/Dockerfile.test
    env_file:
      - ./env/.env.test
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    command: ['sh', '-c', 'npm run test && npm run test:e2e']
