services:
  api:
    build:
      context: ..
      dockerfile: docker/images/api/Dockerfile.dev
    command: ['sh', '-c', 'npm install && npm run start:dev']
    env_file:
      - ./env/.env.dev
    ports:
      - '${PORT}:3000'
    volumes:
      - ..:/usr/src/app
      - dev_node_modules:/usr/src/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    restart: unless-stopped

volumes:
  dev_node_modules:
