apiVersion: 1

datasources:
  - name: NestMetrics
    uid: nestmetrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      timeInterval: 15s
